baseURL = "https://pakstech.download/"
languageCode = "en-us"
title = "Päkstech.dev"
theme = "bloggeri"
paginate = 4

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.main]]
    name = "Categories"
    url = "/categories"

[[menu.main]]
    name = "Contact"
    url = "/contact"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/pakstech"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
    pre = "<i class='fab fa-youtube'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/pakstech"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

[params]
    description = "My site description"
    author = "Janne Kemppainen"
    authorImage = "/images/janne.jpg"

[related]
    threshold = 0
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10


    
    
